#
#
# Makefile for File I/O programs
#
#

write-0: write-0.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o write-0 write-0.c -lcs50 -lm

read-0: read-0.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o read-0 read-0.c -lcs50 -lm

read-1: read-1.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o read-1 read-1.c -lcs50 -lm

read-2: read-2.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o read-2 read-2.c -lcs50 -lm		
