#
#
# Makefile for pset4 codes
#
#

getChar: getChar.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o getChar getChar.c -lcs50 -lm

getChar-1: getChar-1.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o getChar-1 getChar-1.c -lcs50 -lm

getChar-2: getChar-2.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o getChar-2 getChar-2.c -lcs50 -lm

putch: putch.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o putch putch.c -lcs50 -lm

charPoint: charPoint.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o charPoint charPoint.c -lcs50 -lm

charPoint-1: charPoint-1.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o charPoint-1 charPoint-1.c -lcs50 -lm

charPoint-2: charPoint-2.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o charPoint-2 charPoint-2.c -lcs50 -lm

imdb: imdb.c sort.c sort.h
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o imdb imdb.c sort.c -lcs50 -lm

structure: structure.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o structure structure.c -lcs50 -lm

structureH: structureHeap.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o structureH structureHeap.c -lcs50 -lm

testError: testError.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o testError testError.c -lcs50 -lm

TommD: TommDate.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o TommD TommDate.c -lcs50 -lm

TommD-1: TommDate-1.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o TommD-1 TommDate-1.c -lcs50 -lm

TommD-2: TommDate-2.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o TommD-2 TommDate-2.c -lcs50 -lm


leapY: leapYear.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o leapY leapYear.c -lcs50 -lm

TommT: TommTime.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o TommT TommTime.c -lcs50 -lm

structA: structArray.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o structA structArray.c -lcs50 -lm

event: Event.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o event Event.c -lcs50 -lm

structure-1: structure-1.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o structure-1 structure-1.c -lcs50 -lm

linkl: linkedList.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o linkl linkedList.c -lcs50 -lm

strleng: stringLength.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o strleng stringLength.c -lcs50 -lm
const-0: const.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o const-0 const.c -lcs50 -lm

copyS: copyString.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o copyS copyString.c -lcs50 -lm

clean:
	rm -f *.o core a.out getChar getChar-1 getChar-2 putch charPoint charPoint-1 charPoint-2 imdb structure structureH testError TommD TommD-1 TommD-2 leapY TommT structA event copyS const-0 linkl strleng structure-1
