/**
 * generate.c
 *
 * Computer Science 50
 * Problem Set 3
 *
 * Generates pseudorandom numbers in [0,LIMIT), one per line.
 *
 * Usage: generate n [s]
 *
 * where n is number of pseudorandom numbers to print
 * and s is an optional seed
 */

#define _XOPEN_SOURCE

#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// constant
#define LIMIT 65536

int main(int argc, string argv[])
{
    // TODO: Execute this if block only if the number command line arguments are not 2 and 3. Tell the user about the correct usage. Return integer 1.
    if (argc != 2 && argc != 3)
    {
        printf("Usage: generate n [s]\n");
        return 1;
    }

    // TODO: Copy argument vector of index 1 to n by first converting the charachter inputs to integer with the function atoi();
    int n = atoi(argv[1]);

    // TODO: If argc is 3 then convert it to an integer from a charachter first by passing argv[2] in atoi() and then cast it to data type long int and hence pass the resultant integer to srand48 to seed the rand function. If argc is not 3 then pass a NULL to time function and hence pass it, after casting to long int, to srand48();
    if (argc == 3)
    {
        srand48((long int) atoi(argv[2]));
    }
    else
    {
        srand48((long int) time(NULL));
    }

    // TODO: Generate (n - 1) random numbers. Multiply each random number generated by drand48() and multiply it by the constant limit 65536, then cast the resultant number to  an int and print the final number.
    for (int i = 0; i < n; i++)
    {
        printf("%i\n", (int) (drand48() * LIMIT));
    }

    // success
    return 0;
}
